sonata_admin:
    title: 'Web Shop'
    title_logo: 'images/logo_title.png'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left, settings: { groups: [Web Shop]} }
            - { type: sonata.block.service.stats, position: right }

    assets:
        extra_javascripts: [ ]
    options:
        use_stickyforms: false
    security:
        handler: sonata.admin.security.handler.role
    templates:
        layout: '/admin/standard_layout_extended.html.twig'
        edit: '/admin/CRUD/edit_extended.html.twig'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

