sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    assets:
        extra_javascripts: ['app.js']
    options:
        use_stickyforms: false
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
